### ISSUE TITLE
Error `git: command not found` on GitHub-hosted arm64 runner that got GfW installed at runtime

### ISSUE THREAD

**Issue by dennisameling** [git-for-windows/setup-git-for-windows-sdk#951]
While working on https://github.com/dennisameling-org/git-for-windows-automation/pull/1, I ran into a weird issue where the `setup-git-for-windows-sdk` action didn't work, even though I manually installed it in an earlier step ([the arm64 image doesn't have GfW installed yet](https://github.com/actions/partner-runner-images/issues/19)).

I've created a consistent reproducer [here](https://github.com/dennisameling-org/git-for-windows-automation/pull/2), which shows some interesting behavior:
- The first attempt to use `setup-git-for-windows-sdk` [fails](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:3:15) with `Error: spawn C:/Program Files/Git/cmd/git.exe ENOENT`
- I then install Git for Windows and add it to the path
- In the second attempt, it actually [uses the Git executable](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:5:18) to clone `git-sdk-arm64` and `build-extra`. However, `Creating build-installers artifact` still [fails](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:5:139) with `.tmp/build-extra/please.sh: line 106: git: command not found`.

## What I did so far to debug this issue

- In https://github.com/dennisameling/setup-git-for-windows-sdk/pull/3, I added some logging to better understand the environment variables that get set by the NodeJS process when it invokes `bash.exe` from the `C:/Program Files/Git/usr/bin` folder (`gitForWindowsUsrBinPath`). [Here](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774266188/job/29875914336?pr=2#step:5:49) you can see the `PATH` value that NodeJS passes to the `bash.exe` process. Bash itself, however, reports [this](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774266188/job/29875914336?pr=2#step:5:52), where it seems like `C:/Program Files/Git/usr/bin` got replaced with simply `/usr/bin` (I assume this is expected behavior). This folder doesn't seem to contain the `git.exe` executable.
- I have a strong feeling that this issue hasn't popped up before because both GitHub-hosted runners *and* our self-hosted runners have Git for Windows pre-installed, **before** (!!!) the GitHub runner agent starts and loads the environment variables from the OS. I added a `which git` line, which resulted in the following:
  - [GitHub-hosted arm64 runner](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:5:129) (without Git preinstalled, but installed it in the pipeline itself): `which: no git in (/usr/bin:/bin:/.....)`
  - [GitHub-hosted x64 runner](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877653163#step:2:28) (with GfW preinstalled): `/cmd/git` (so it somehow found Git in the `/cmd` folder, even though it doesn't show in the path??)

## What I did to work around the issue

[Here](https://github.com/dennisameling/setup-git-for-windows-sdk/pull/2/files#diff-2ea4750851b34def3ddd617afa64e175a87064a29dbb9e6fd20eee6f1dd6dc93R212), I just explicitly added `PATH="/c/Program Files/Git/bin:$PATH"` to `please.sh`, so that it could find _something_ to work with.

Noe that this issue will probably disappear as soon as GfW [gets preinstalled](https://github.com/actions/partner-runner-images/issues/19) on GitHub-hosted ARM64 runners, but I think we could make the `setup-git-for-windows-sdk` action more resilient to this type of issue moving forward.

I'm happy to implement a fix if you could point me in the right direction. Thanks!

**Comment by rimrul** [comment]
Bash itself, however, reports [this](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774266188/job/29875914336?pr=2#step:5:52), where it seems like C:/Program Files/Git/usr/bin got replaced with simply /usr/bin (I assume this is expected behavior).

It is expected.

> This folder doesn't seem to contain the git.exe executable.

That is expected, too. `/usr/bin/git.exe` would be MSYS2 Git. We're looking for `/cmd/git.exe` or `/mingw64/git.exe`.

> [GitHub-hosted x64 runner](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877653163#step:2:28) (with GfW preinstalled): /cmd/git (so it somehow found Git in the /cmd folder, even though it doesn't show in the path??)

`/cmd` is on the `PATH` there.

> […]`Program Files/nodejs:/cmd:/mingw64/bin:/usr/bin:/c/Program Files/GitHub CLI`[…]

> I have a strong feeling that this issue hasn't popped up before because both GitHub-hosted runners and our self-hosted runners have Git for Windows pre-installed, before (!!!) the GitHub runner agent starts and loads the environment variables from the OS.

I think this feeling is correct.

> In the second attempt, it actually [uses the Git executable](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:5:18) to clone git-sdk-arm64 and build-extra. However, Creating build-installers artifact still [fails](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:5:139) with .tmp/build-extra/please.sh: line 106: git: command not found.

The cloning steps call the `git.exe` they want with an absolute path, but the `please.sh` step just calls `git`.

**Comment by dscho** [comment]
Maybe [this code](https://github.com/git-for-windows/git/blob/v2.46.0.windows.1/compat/mingw.c#L3430-L3444) is the culprit for the behavior where `/cmd/git.exe` is found but Git can then not find its commands?

But that does not really match the error message, which looks more as if `/cmd/git.exe` does not find `/clangarm64/bin/git.exe` (and then let _that_ do the actual work), [even though it should find it](https://github.com/git-for-windows/MINGW-packages/blob/310c68183ca24477f8e76f13f5ee50c475d47dcb/mingw-w64-git/git-wrapper.c#L139-L152).

**Comment by dscho** [comment]
> > looks more as if `/cmd/git.exe` does not find `/clangarm64/bin/git.exe`
> 
> I think it's just [bash doesn't have `/cmd` or `/clangarm64/bin` or `/mingw64/bin` on the path when calling `please.sh`](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/main/src/git.ts#L199-L223)

Good point. It happens to work on hosted runners because `git.exe` is _already_ in the `PATH` there.

So we'd need to change [this code](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/2c7b814daef4870728b239b188123fbe6d7f89fb/src/git.ts#L219) around from someting like:

```typescript
export const gitForWindowsUsrBinPath = `${gitRoot}/usr/bin`
[...]
              PATH: `${gitForWindowsUsrBinPath}${delimiter}${process.env.PATH}`
```

to something like:

```typescript
export const gitForWindowsBinPaths =
  ['clangarm64', 'mingw64', 'mingw32', 'usr'].map(p => `${gitRoot}/${p}/bin`)
[...]
              PATH: `${gitForWindowsBinPaths.join(delimiter)}${delimiter}${process.env.PATH}`
```

I pushed something along those lines into my fork [as `fix-on-arm64` branch](https://github.com/git-for-windows/setup-git-for-windows-sdk/compare/main...dscho:setup-git-for-windows-sdk:fix-on-arm64).

@dennisameling could you please try running this (switching out `uses: dscho/setup-git-for-windows-sdk@fix-on-arm64` for `uses: git-for-windows/setup-git-for-windows-sdk@v1` should do the trick)? This should even run _without_ installing Git for Windows, as it should simply use the runner's own MinGit in that case.

**Comment by dennisameling** [comment]
> @dennisameling could you please try running this (switching out `uses: dscho/setup-git-for-windows-sdk@fix-on-arm64` for `uses: git-for-windows/setup-git-for-windows-sdk@v1` should do the trick)?

That [worked](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10790615911/job/29926204930), thank you!!

> This should even run _without_ installing Git for Windows, as it should simply use the runner's own MinGit in that case.

It [doesn't](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10790615911/job/29926204930#step:3:15), because the `cloning git-sdk-arm64` step still expects `C:/Program Files/Git/cmd/git.exe` to be present. But I'd say that's outside the scope of this issue.

I was working on a [similar fix](https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/953), and ended up extracting the `spawn` logic into a wrapper and adding tests. Curious to hear if you think that'd still add value to this repo.

**Comment by dscho** [comment]
> It [doesn't](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10790615911/job/29926204930#step:3:15), because the `cloning git-sdk-arm64` step still expects `C:/Program Files/Git/cmd/git.exe` to be present.

Hmm. But [that `clone()` call](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/2c7b814daef4870728b239b188123fbe6d7f89fb/src/git.ts#L168) implicitly spawns `git.exe` at [`gitExePath`](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/2c7b814daef4870728b239b188123fbe6d7f89fb/src/git.ts#L55), which has previously been [set to `${gitRoot}/cmd/git.exe`](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/2c7b814daef4870728b239b188123fbe6d7f89fb/src/git.ts#L15), and that `gitRoot` [should find the agent runner's MinGit](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/2c7b814daef4870728b239b188123fbe6d7f89fb/src/git.ts#L10-L12). Does that not exist?

**Comment by dennisameling** [comment]
> Does that not exist?

[It doesn't, indeed](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10795104333/job/29940956517). By default, the GitHub Actions Runner doesn't seem to have any flavor of Git pre-installed. [It only seems to have NodeJS installed](https://github.com/actions/runner/blob/ddf41af7678a8bc585d9e6b8ab70d941cdb687b2/src/Misc/externals.sh#L142). Having Git pre-installed [only seems to be the case](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#tools) on the default GitHub-hosted runners, like `windows-2019` and `windows-2022`.

Even the `AGENT_HOMEDIRECTORY` environment variable [doesn't exist](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10795104333/job/29941398587#step:2:1) at runtime ([docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)). Isn't that a leftover from the [Azure Pipelines days](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services)?

**Comment by dscho** [comment]
> > Does that not exist?
> 
> [It doesn't, indeed](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10795104333/job/29940956517). By default, the GitHub Actions Runner doesn't seem to have any flavor of Git pre-installed.

Huh. I thought it _needed_ Git to run `actions/checkout` and the likes?

> Even the `AGENT_HOMEDIRECTORY` environment variable [doesn't exist](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10795104333/job/29941398587#step:2:1) at runtime ([docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)).
> Isn't that a leftover from the [Azure Pipelines days](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services)?

Hmm. Possibly. Maybe `RUNNER_TOOL_CACHE` has it?

**Comment by dennisameling** [comment]
> Huh. I thought it _needed_ Git to run `actions/checkout` and the likes?

Apparently not, as can be seen [here](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10774772335/job/29877652733#step:2:22):

```
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
```
It falls back to the GitHub REST API if Git isn't installed. However, in my earlier testing, that _did_ [cause issues later down the line](https://github.com/dennisameling-org/git-for-windows-automation/actions/runs/10753566575/job/29823138974#step:4:37): 

```
fatal: not a git repository (or any of the parent directories): .git
```

> Hmm. Possibly. Maybe `RUNNER_TOOL_CACHE` has it?

Negative. Looks like that folder doesn't even exist on a fresh installation of the Runner. So it looks like GfW really doesn't come bundled with the runner itself, only NodeJS.

<img width="798" alt="GitHub Actions runner folder layout" src="https://github.com/user-attachments/assets/61038dba-4253-4063-9ca5-3ce30a39a76f">

**Comment by dscho** [comment]
> So it looks like GfW really doesn't come bundled with the runner itself, only NodeJS.

Okay. Together with other insights I recently had (like: why do we have to clone Git for Windows' minimal SDK over and over again, when we are [taking pains to look for the latest revision for which `ci-artifacts` passed successfully](https://github.com/git-for-windows/setup-git-for-windows-sdk/blob/04d06f123fa6173460afbdbdac8be4128c41a7fc/src/git.ts#L131-L151)), I am coming to the conclusion that we need to change the architecture.

Instead of doing a sparse, partial & shallow clone of the Git for Windows SDK _every single time_ the `setup-git-for-windows-sdk` Action runs (and does not find a cached version), why not upload the artifact right after the `ci-artifacts` run succeeded, to a public location?

I'll tell you why: I once looked into doing that, considering [GitHub Packages](https://github.com/features/packages). But they have [rather strict retention rules](https://docs.github.com/en/packages/learn-github-packages/deleting-and-restoring-a-package#package-deletion-and-restoration-support-on-github) and we definitely do not need to retain anything but the latest working minimal-sdk artifact. (And I don't want to waste resources unnecessarily, even if someone else pays for them.) So I looked into uploading that artifact to Azure Blobs, but [had to pull the plug in one big hurry](https://github.com/git-for-windows/git-sdk-64/commit/e51b79eef9230f4eb4a89719030b26206a33f947) because it threatened to blow my Azure budget. So I gave up on that plan and instead went with the "partial, shallow, sparse clone & then cache" plan.

Turns out that other people had the same problem and became much more creative than myself. For example, the MSYS2 project needs to maintain a "srcinfo" cache where it stores information about all the latest package versions that were built and uploaded to their Pacman repository. And they use [a GitHub release](https://github.com/msys2/MINGW-packages/releases/tag/srcinfo-cache) for that. Where they overwrite the release assets with whatever becomes the current version, over and over and over again.

We can do the same!

So here's my current plan: Modify [the `ci-artifacts` GitHub workflow](https://github.com/git-for-windows/git-sdk-64/blob/HEAD/.github/workflows/ci-artifacts.yml) to upload the minimal-sdk artifact to a dedicated GitHub release in git-for-windows/git-sdk-64 (after the tests concluded successfully, of course). I want to force-update the tag associated with this GitHub release to point to the revision from which the artifact was built. I also want to provide the artifact both in the form of a `.tar.gz` as well as a self-extracting `.7z` file, the former for historical reasons, the latter to avoid problems on self-hosted runners where there is no pre-installed way to extract tar files.

The biggest downside of this strategy is that it won't work with anything else but the git-for-windows/git-sdk-64 repository because it requires that GitHub release, and requires effort to ensure that the release asset(s) are kept up to date. In particular, it won't work with the git-sdk-arm64 repository unless we start running that `ci-artifacts` GitHub workflow there, too. But we could start doing that soon, anyway.

A slightly smaller downside is that this locks the door for the idea to potentially use the minimal SDK for an arbitrary git-sdk-64 revision. But I never really added the code to enable that, anyway, so that's not such a big deal. In any case, it should be relatively easy to resurrect the code if the need for that feature should arise in the future.

**Comment by dennisameling** [comment]
> And they use [a GitHub release](https://github.com/msys2/MINGW-packages/releases/tag/srcinfo-cache) for that. Where they overwrite the release assets with whatever becomes the current version, over and over and over again.
>
> We can do the same!

That makes a lot of sense to me!

> I also want to provide the artifact both in the form of a `.tar.gz` as well as a self-extracting `.7z` file, the former for historical reasons, the latter to avoid problems on self-hosted runners where there is no pre-installed way to extract tar files.

Windows itself [has had `tar` built-in](https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/) for a while. It's definitely there on self-hosted runners as well. It's located at `C:\Windows\System32\tar.exe`. Could that be used to work with those `.tar.gz` files?

Let me know if I can help with anything!

**Comment by dscho** [comment]
> Windows itself [has had `tar` built-in](https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/) for a while. It's definitely there on self-hosted runners as well. It's located at `C:\Windows\System32\tar.exe`. Could that be used to work with those `.tar.gz` files?

In my tests, this indeed works, and it works quite well, and blows `/usr/bin/tar.exe` out of the water. 4.3 seconds vs 6.5 seconds out of the water.

Here is step 1: https://github.com/git-for-windows/git-sdk-64/pull/87. Step 2 will be do adjust `setup-for-windows-sdk` to make use of that continuous release (in particular, measuring the speed to confirm that downloading and extracting the `.zip` file is the fastest).

Step 3 will be to set up the same changes in `git-sdk-arm64`. But I am a bit worried about that now, having realized yesterday that one of the self-hosted runners kept running since September 4th, blowing through ⅐ of my Azure credits... If that keeps happening, I'll end up with some serious trouble due to blocked Azure services (including GitGitGadget, for example).

**Comment by dennisameling** [comment]
> Step 2 will be do adjust `setup-for-windows-sdk` to make use of that continuous release (in particular, measuring the speed to confirm that downloading and extracting the `.zip` file is the fastest).

Let me know if I can be of any help there.

> Step 3 will be to set up the same changes in `git-sdk-arm64`. But I am a bit worried about that now, having realized yesterday that one of the self-hosted runners kept running since September 4th, blowing through ⅐ of my Azure credits... If that keeps happening, I'll end up with some serious trouble due to blocked Azure services (including GitGitGadget, for example).

I added a scheduled cleanup job [here](https://github.com/git-for-windows/git-for-windows-automation/pull/60#issuecomment-2051698665) but back then, we decided that we just wanted to rely on webhooks for the time being. So we could probably still add that logic, or accelerate the [switch](https://github.com/git-for-windows/git-for-windows-automation/issues/91) over to GitHub-hosted arm64 runners instead (now in paid GA). I think we'll want to do the latter anyway at some point in the near future, before or after they become freely available for OSS projects (see the linked issue for more details).

**Comment by dscho** [comment]
> I added a scheduled cleanup job [here](https://github.com/git-for-windows/git-for-windows-automation/pull/60#issuecomment-2051698665)

You have a good point. I shouldn't have asked for that commit to be dropped. Here is my attempt to atone: https://github.com/git-for-windows/git-for-windows-automation/pull/93

**Comment by dennisameling** [comment]
> Step 3 will be to set up the same changes in `git-sdk-arm64`

I have a PR in progress that's _almost_ working: https://github.com/git-for-windows/git-sdk-arm64/pull/22

**Comment by dennisameling** [comment]
> Step 2 will be do adjust `setup-for-windows-sdk` to make use of that continuous release (in particular, measuring the speed to confirm that downloading and extracting the `.zip` file is the fastest).

And to wrap things up, [this PR](https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/965) implements step 2. Spoiler alert: it's _incredibly_ fast!
